apiVersion: apps/v1
kind: Deployment
metadata:
  name: moyur-app-deployment
  labels:
    app: moyur-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moyur-app
  template:
    metadata:
      labels:
        app: moyur-app
    spec:
      containers:
      - name: moyur-app
        image: docker.io/renum/rust:v0.0.15
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: moyur-secret
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: moyur-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moyur-secret
              key: DATABASE_PASSWORD
      terminationGracePeriodSeconds: 30
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1

