apiVersion: v1
kind: Secret
metadata:
  name: moyur-secret
type: Opaque
data:
# 데이터베이스 URL = DATABASE_URL=mysql://root:root1234@10.0.12.24:3306/moyur
  DATABASE_URL: bXlzcWw6Ly9yb290OnJvb3QxMjM0QDEwLjAuMTIuMjMxOjMzMDYvbW95dXI=
  DATABASE_USERNAME: cm9vdA==
  DATABASE_PASSWORD: cm9vdDEyMzQ=
